package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1



/**
 * Abonodetalle generated by hbm2java
 */
public class Abonodetalle  implements java.io.Serializable {


     private Integer idabonoDetalle;
     private Abonos abonos;
     private Productos productos;
     private String nombrepro;
     private Integer cantidad;
     private long precioventa;
     private Long total;
     private Integer preccioTrabajo;
     private Integer porcentajeganancia;
     private String alto;
     private String ancho;
     private String fondo;

    public Abonodetalle() {
    }

	
    public Abonodetalle(Abonos abonos, Productos productos, String nombrepro, long precioventa) {
        this.abonos = abonos;
        this.productos = productos;
        this.nombrepro = nombrepro;
        this.precioventa = precioventa;
    }
    public Abonodetalle(Abonos abonos, Productos productos, String nombrepro, Integer cantidad, long precioventa, Long total, Integer preccioTrabajo, Integer porcentajeganancia, String alto, String ancho, String fondo) {
       this.abonos = abonos;
       this.productos = productos;
       this.nombrepro = nombrepro;
       this.cantidad = cantidad;
       this.precioventa = precioventa;
       this.total = total;
       this.preccioTrabajo = preccioTrabajo;
       this.porcentajeganancia = porcentajeganancia;
       this.alto = alto;
       this.ancho = ancho;
       this.fondo = fondo;
    }
   
    public Integer getIdabonoDetalle() {
        return this.idabonoDetalle;
    }
    
    public void setIdabonoDetalle(Integer idabonoDetalle) {
        this.idabonoDetalle = idabonoDetalle;
    }
    public Abonos getAbonos() {
        return this.abonos;
    }
    
    public void setAbonos(Abonos abonos) {
        this.abonos = abonos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getNombrepro() {
        return this.nombrepro;
    }
    
    public void setNombrepro(String nombrepro) {
        this.nombrepro = nombrepro;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public long getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(long precioventa) {
        this.precioventa = precioventa;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    public Integer getPreccioTrabajo() {
        return this.preccioTrabajo;
    }
    
    public void setPreccioTrabajo(Integer preccioTrabajo) {
        this.preccioTrabajo = preccioTrabajo;
    }
    public Integer getPorcentajeganancia() {
        return this.porcentajeganancia;
    }
    
    public void setPorcentajeganancia(Integer porcentajeganancia) {
        this.porcentajeganancia = porcentajeganancia;
    }
    public String getAlto() {
        return this.alto;
    }
    
    public void setAlto(String alto) {
        this.alto = alto;
    }
    public String getAncho() {
        return this.ancho;
    }
    
    public void setAncho(String ancho) {
        this.ancho = ancho;
    }
    public String getFondo() {
        return this.fondo;
    }
    
    public void setFondo(String fondo) {
        this.fondo = fondo;
    }




}


