package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Abonos generated by hbm2java
 */
public class Abonos  implements java.io.Serializable {


     private Integer idabonos;
     private Cliente cliente;
     private Empleado empleado;
     private Long precioTotal;
     private Long montoabono;
     private Long saldofinal;
     private Date fecharegistro;
     private Set abonodetalles = new HashSet(0);
     private Set abonosecundarios = new HashSet(0);

    public Abonos() {
    }

	
    public Abonos(Cliente cliente, Empleado empleado, Date fecharegistro) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.fecharegistro = fecharegistro;
    }
    public Abonos(Cliente cliente, Empleado empleado, Long precioTotal, Long montoabono, Long saldofinal, Date fecharegistro, Set abonodetalles, Set abonosecundarios) {
       this.cliente = cliente;
       this.empleado = empleado;
       this.precioTotal = precioTotal;
       this.montoabono = montoabono;
       this.saldofinal = saldofinal;
       this.fecharegistro = fecharegistro;
       this.abonodetalles = abonodetalles;
       this.abonosecundarios = abonosecundarios;
    }
   
    public Integer getIdabonos() {
        return this.idabonos;
    }
    
    public void setIdabonos(Integer idabonos) {
        this.idabonos = idabonos;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Long getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Long precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Long getMontoabono() {
        return this.montoabono;
    }
    
    public void setMontoabono(Long montoabono) {
        this.montoabono = montoabono;
    }
    public Long getSaldofinal() {
        return this.saldofinal;
    }
    
    public void setSaldofinal(Long saldofinal) {
        this.saldofinal = saldofinal;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set getAbonodetalles() {
        return this.abonodetalles;
    }
    
    public void setAbonodetalles(Set abonodetalles) {
        this.abonodetalles = abonodetalles;
    }
    public Set getAbonosecundarios() {
        return this.abonosecundarios;
    }
    
    public void setAbonosecundarios(Set abonosecundarios) {
        this.abonosecundarios = abonosecundarios;
    }




}


