package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idciudad;
     private Departamento departamento;
     private String nombreCiu;
     private Set empleados = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(int idciudad, Departamento departamento, String nombreCiu) {
        this.idciudad = idciudad;
        this.departamento = departamento;
        this.nombreCiu = nombreCiu;
    }
    public Ciudad(int idciudad, Departamento departamento, String nombreCiu, Set empleados, Set clientes) {
       this.idciudad = idciudad;
       this.departamento = departamento;
       this.nombreCiu = nombreCiu;
       this.empleados = empleados;
       this.clientes = clientes;
    }
   
    public int getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(int idciudad) {
        this.idciudad = idciudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreCiu() {
        return this.nombreCiu;
    }
    
    public void setNombreCiu(String nombreCiu) {
        this.nombreCiu = nombreCiu;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


