package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private Ciudad ciudad;
     private Tipodocumento tipodocumento;
     private String nombre;
     private String apellidos;
     private String numeroDocumentoC;
     private String correoElectronico;
     private String telefono;
     private String direccion;
     private Set cotizacions = new HashSet(0);
     private Set abonoses = new HashSet(0);
     private Set facturases = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Ciudad ciudad, Tipodocumento tipodocumento, String nombre, String numeroDocumentoC) {
        this.ciudad = ciudad;
        this.tipodocumento = tipodocumento;
        this.nombre = nombre;
        this.numeroDocumentoC = numeroDocumentoC;
    }
    public Cliente(Ciudad ciudad, Tipodocumento tipodocumento, String nombre, String apellidos, String numeroDocumentoC, String correoElectronico, String telefono, String direccion, Set cotizacions, Set abonoses, Set facturases) {
       this.ciudad = ciudad;
       this.tipodocumento = tipodocumento;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.numeroDocumentoC = numeroDocumentoC;
       this.correoElectronico = correoElectronico;
       this.telefono = telefono;
       this.direccion = direccion;
       this.cotizacions = cotizacions;
       this.abonoses = abonoses;
       this.facturases = facturases;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNumeroDocumentoC() {
        return this.numeroDocumentoC;
    }
    
    public void setNumeroDocumentoC(String numeroDocumentoC) {
        this.numeroDocumentoC = numeroDocumentoC;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


