package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion  implements java.io.Serializable {


     private Integer idcotizacion;
     private Cliente cliente;
     private Empleado empleado;
     private Long subtotal;
     private Long iva;
     private Long preciototal;
     private Date fechacotizacion;
     private Set cotizaciondetalles = new HashSet(0);

    public Cotizacion() {
    }

	
    public Cotizacion(Cliente cliente, Empleado empleado, Date fechacotizacion) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.fechacotizacion = fechacotizacion;
    }
    public Cotizacion(Cliente cliente, Empleado empleado, Long subtotal, Long iva, Long preciototal, Date fechacotizacion, Set cotizaciondetalles) {
       this.cliente = cliente;
       this.empleado = empleado;
       this.subtotal = subtotal;
       this.iva = iva;
       this.preciototal = preciototal;
       this.fechacotizacion = fechacotizacion;
       this.cotizaciondetalles = cotizaciondetalles;
    }
   
    public Integer getIdcotizacion() {
        return this.idcotizacion;
    }
    
    public void setIdcotizacion(Integer idcotizacion) {
        this.idcotizacion = idcotizacion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Long subtotal) {
        this.subtotal = subtotal;
    }
    public Long getIva() {
        return this.iva;
    }
    
    public void setIva(Long iva) {
        this.iva = iva;
    }
    public Long getPreciototal() {
        return this.preciototal;
    }
    
    public void setPreciototal(Long preciototal) {
        this.preciototal = preciototal;
    }
    public Date getFechacotizacion() {
        return this.fechacotizacion;
    }
    
    public void setFechacotizacion(Date fechacotizacion) {
        this.fechacotizacion = fechacotizacion;
    }
    public Set getCotizaciondetalles() {
        return this.cotizaciondetalles;
    }
    
    public void setCotizaciondetalles(Set cotizaciondetalles) {
        this.cotizaciondetalles = cotizaciondetalles;
    }




}


