package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private String nombreDept;
     private Set ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento, String nombreDept) {
        this.iddepartamento = iddepartamento;
        this.nombreDept = nombreDept;
    }
    public Departamento(int iddepartamento, String nombreDept, Set ciudads) {
       this.iddepartamento = iddepartamento;
       this.nombreDept = nombreDept;
       this.ciudads = ciudads;
    }
   
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getNombreDept() {
        return this.nombreDept;
    }
    
    public void setNombreDept(String nombreDept) {
        this.nombreDept = nombreDept;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


