package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Ciudad ciudad;
     private Rol rol;
     private Tipodocumento tipodocumento;
     private String numeroDocumento;
     private String nombre;
     private String apellidos;
     private int edad;
     private boolean genero;
     private Date fechaNacimiento;
     private String correoElectronico;
     private String password;
     private Date fechaIngreso;
     private String telefono;
     private String direccion;
     private Set abonosecundarios = new HashSet(0);
     private Set abonoses = new HashSet(0);
     private Set cotizacions = new HashSet(0);
     private Set facturases = new HashSet(0);
     private Set sueldos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Ciudad ciudad, Rol rol, Tipodocumento tipodocumento, String numeroDocumento, String nombre, String apellidos, int edad, boolean genero, Date fechaNacimiento, String correoElectronico, String password, Date fechaIngreso) {
        this.ciudad = ciudad;
        this.rol = rol;
        this.tipodocumento = tipodocumento;
        this.numeroDocumento = numeroDocumento;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.edad = edad;
        this.genero = genero;
        this.fechaNacimiento = fechaNacimiento;
        this.correoElectronico = correoElectronico;
        this.password = password;
        this.fechaIngreso = fechaIngreso;
    }
    public Empleado(Ciudad ciudad, Rol rol, Tipodocumento tipodocumento, String numeroDocumento, String nombre, String apellidos, int edad, boolean genero, Date fechaNacimiento, String correoElectronico, String password, Date fechaIngreso, String telefono, String direccion, Set abonosecundarios, Set abonoses, Set cotizacions, Set facturases, Set sueldos) {
       this.ciudad = ciudad;
       this.rol = rol;
       this.tipodocumento = tipodocumento;
       this.numeroDocumento = numeroDocumento;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.genero = genero;
       this.fechaNacimiento = fechaNacimiento;
       this.correoElectronico = correoElectronico;
       this.password = password;
       this.fechaIngreso = fechaIngreso;
       this.telefono = telefono;
       this.direccion = direccion;
       this.abonosecundarios = abonosecundarios;
       this.abonoses = abonoses;
       this.cotizacions = cotizacions;
       this.facturases = facturases;
       this.sueldos = sueldos;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public boolean isGenero() {
        return this.genero;
    }
    
    public void setGenero(boolean genero) {
        this.genero = genero;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getAbonosecundarios() {
        return this.abonosecundarios;
    }
    
    public void setAbonosecundarios(Set abonosecundarios) {
        this.abonosecundarios = abonosecundarios;
    }
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }
    public Set getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set cotizacions) {
        this.cotizacions = cotizacions;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }
    public Set getSueldos() {
        return this.sueldos;
    }
    
    public void setSueldos(Set sueldos) {
        this.sueldos = sueldos;
    }




}


