package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1



/**
 * Puertas generated by hbm2java
 */
public class Puertas  implements java.io.Serializable {


     private Integer idpuertas;
     private String nombre;
     private Integer preciocot;

    public Puertas() {
    }

	
    public Puertas(String nombre) {
        this.nombre = nombre;
    }
    public Puertas(String nombre, Integer preciocot) {
       this.nombre = nombre;
       this.preciocot = preciocot;
    }
   
    public Integer getIdpuertas() {
        return this.idpuertas;
    }
    
    public void setIdpuertas(Integer idpuertas) {
        this.idpuertas = idpuertas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPreciocot() {
        return this.preciocot;
    }
    
    public void setPreciocot(Integer preciocot) {
        this.preciocot = preciocot;
    }




}


