package Pojos;
// Generated 15-abr-2016 20:51:33 by Hibernate Tools 4.3.1



/**
 * Vitrinas generated by hbm2java
 */
public class Vitrinas  implements java.io.Serializable {


     private Integer idvitrinas;
     private String nombre;
     private Integer preciocot;

    public Vitrinas() {
    }

	
    public Vitrinas(String nombre) {
        this.nombre = nombre;
    }
    public Vitrinas(String nombre, Integer preciocot) {
       this.nombre = nombre;
       this.preciocot = preciocot;
    }
   
    public Integer getIdvitrinas() {
        return this.idvitrinas;
    }
    
    public void setIdvitrinas(Integer idvitrinas) {
        this.idvitrinas = idvitrinas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPreciocot() {
        return this.preciocot;
    }
    
    public void setPreciocot(Integer preciocot) {
        this.preciocot = preciocot;
    }




}


